# Generated by Django 3.1.5 on 2021-01-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
